name: Frontend CI

on:
  push:
    paths:
      - "app/public/wp-content/react-app/**"
  pull_request:
    paths:
      - "app/public/wp-content/react-app/**"

jobs:
  build-react-app:
    runs-on: ubuntu-latest

    # Everything below runs inside the react-app folder
    defaults:
      run:
        working-directory: app/public/wp-content/react-app

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: |
            app/public/wp-content/react-app/package-lock.json

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔨 Build React app
        run: npm run build

      - name: ✅ Check for build output
        run: test -f build/index.html
